name: Build for Mystrix 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
        
    - name: Cache Git modules
      uses: actions/cache@v4.1.0
      with:
        path: |
          .git/modules  # Cache Git module data for submodules
          lib/          # Cache your submodule directories if they are in 'lib'
          espressif/idf:release-v5.0 # ESP IDF
        key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
        restore-keys: |
          ${{ runner.os }}-submodules-
          
    - name: Update git submodules
      if: steps.cache-submodule.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Initialize and update submodules if not cached
      run: |
        if [ ! -d ".git/modules" ]; then
          echo "Submodules not cached, initializing..."
          git submodule update --init --recursive
        else
          echo "Submodules are cached, skipping initialization."
        fi
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    
